name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman
        uses: jasonlong/github-readme-pacman@main
        with:
          github_user_name: ${{ github.repository_owner }}
